/**
 * Concatenates 07-agent-system-prompt.md (fenced code block) + 06-site-knowledge.md
 * and writes to apps/web/lib/agent-system-prompt.ts as an exported constant.
 *
 * Also copies 06-site-knowledge.md to apps/web/data/site-knowledge.md for runtime
 * availability (optional; constant is the source of truth for the API proxy).
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const specDir = resolve(here, "../../../docs/spec/the-tile");
const promptMd = resolve(specDir, "07-agent-system-prompt.md");
const knowledgeMd = resolve(specDir, "06-site-knowledge.md");
const outTs = resolve(here, "../lib/agent-system-prompt.ts");
const outData = resolve(here, "../data/site-knowledge.md");

if (!existsSync(promptMd) || !existsSync(knowledgeMd)) {
  console.warn(`[build-agent-context] spec files missing; skipping.`);
  process.exit(0);
}

const promptSrc = readFileSync(promptMd, "utf8");
const knowledge = readFileSync(knowledgeMd, "utf8");

// Extract the first fenced code block — that's the populated system prompt.
const fenceMatch = promptSrc.match(/```(?:[a-zA-Z0-9_-]*)?\n([\s\S]*?)\n```/);
const systemPrompt = fenceMatch ? fenceMatch[1] : promptSrc;

const combined = `${systemPrompt}\n\nSITE KNOWLEDGE:\n${knowledge}`;

mkdirSync(dirname(outTs), { recursive: true });
mkdirSync(dirname(outData), { recursive: true });

// Escape backticks and ${ for template literal.
const escaped = combined.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

const ts = `// AUTO-GENERATED by scripts/build-agent-context.ts — do not edit.
// Rebuilt from docs/spec/the-tile/07-agent-system-prompt.md + 06-site-knowledge.md.

export const AGENT_SYSTEM_PROMPT = \`${escaped}\`;

export const AGENT_SYSTEM_PROMPT_CHARS = ${combined.length};
`;

writeFileSync(outTs, ts, "utf8");
writeFileSync(outData, combined, "utf8");

console.log(
  `[build-agent-context] wrote ${outTs} (${combined.length.toLocaleString()} chars, ~${Math.round(
    combined.length / 4,
  ).toLocaleString()} tokens)`,
);
