/**
 * Generates apps/web/public/_redirects (Cloudflare Pages format).
 *
 * Reads apps/web/data/seed/products.seed.json and emits a 301 redirect for
 * every product and category that still has an old-site `sourceUrl`, mapping
 * it to the new route in `url` (products) or the category's conventional
 * new path (categories).
 *
 * Cloudflare Pages `_redirects` format:
 *   <old-path> <new-path> <status>
 * One rule per line. Lines starting with `#` are comments.
 *
 * Idempotent and dependency-free — only uses node:fs + node:path + JSON.
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

interface SeedProduct {
  id?: string;
  url?: string;
  sourceUrl?: string | null;
}

interface SeedCategory {
  id?: string;
  type?: string;
  sourceUrl?: string | null;
}

interface ProductsSeed {
  products?: SeedProduct[];
  categories?: SeedCategory[];
}

interface RedirectRule {
  from: string;
  to: string;
  status: number;
}

const here = dirname(fileURLToPath(import.meta.url));
const seedPath = resolve(here, "../data/seed/products.seed.json");
const outPath = resolve(here, "../public/_redirects");

// Category id → new route. Effects live at /collections/<id>; usage
// categories live at /usage/<id> (per 02-information-architecture.md §1).
function newPathForCategory(cat: SeedCategory): string | null {
  if (!cat.id) return null;
  if (cat.type === "effect") return `/collections/${cat.id}`;
  if (cat.type === "usage") return `/usage/${cat.id}`;
  return null;
}

// Pull the path portion out of an absolute or relative source URL.
// Handles the-tile.com absolute URLs and raw `/foo.html` paths.
function pathFromSourceUrl(sourceUrl: string): string | null {
  try {
    const u = sourceUrl.startsWith("http")
      ? new URL(sourceUrl)
      : new URL(sourceUrl, "https://www.the-tile.com");
    // Preserve the leading slash; drop query + hash (rare in the Weebly scrape
    // but defensive).
    return u.pathname || null;
  } catch {
    return null;
  }
}

function collectRules(): RedirectRule[] {
  const raw = readFileSync(seedPath, "utf8");
  const seed: ProductsSeed = JSON.parse(raw);
  const rules: RedirectRule[] = [];

  // Products
  for (const p of seed.products ?? []) {
    if (!p.sourceUrl || !p.url) continue;
    const from = pathFromSourceUrl(p.sourceUrl);
    if (!from || from === "/") continue;
    rules.push({ from, to: p.url, status: 301 });
  }

  // Categories
  for (const c of seed.categories ?? []) {
    if (!c.sourceUrl) continue;
    const from = pathFromSourceUrl(c.sourceUrl);
    const to = newPathForCategory(c);
    if (!from || from === "/" || !to) continue;
    rules.push({ from, to, status: 301 });
  }

  // Manual extras — top-level Weebly pages the scrape didn't cover.
  const extras: RedirectRule[] = [
    { from: "/home.html", to: "/", status: 301 },
    { from: "/index.html", to: "/", status: 301 },
    { from: "/contact-us.html", to: "/contact", status: 301 },
    { from: "/about-us.html", to: "/about", status: 301 },
    { from: "/our-brands.html", to: "/brands", status: 301 },
    { from: "/news.html", to: "/journal", status: 301 },
  ];
  for (const e of extras) rules.push(e);

  // De-duplicate by old path — first wins.
  const seen = new Set<string>();
  const deduped: RedirectRule[] = [];
  for (const r of rules) {
    if (seen.has(r.from)) continue;
    seen.add(r.from);
    deduped.push(r);
  }

  // Stable sort: longest path first so more-specific paths match before
  // parents. (Cloudflare Pages _redirects is first-match-wins top-to-bottom.)
  deduped.sort((a, b) => b.from.length - a.from.length || a.from.localeCompare(b.from));

  return deduped;
}

function render(rules: RedirectRule[]): string {
  const header = [
    "# _redirects — generated by apps/web/scripts/generate-redirects.ts",
    "# 301s from the old Weebly site. Do not edit by hand — edit the seed.",
    "",
  ].join("\n");
  const body = rules.map((r) => `${r.from} ${r.to} ${r.status}`).join("\n");
  return `${header}${body}\n`;
}

function main(): void {
  const rules = collectRules();
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, render(rules), "utf8");
  // eslint-disable-next-line no-console
  console.log(`[generate-redirects] wrote ${rules.length} rules → ${outPath}`);
}

main();
