import { listPulses } from "@/lib/analytics/pulse";
import { dailyAnomalies } from "@/lib/analytics/queries";
import { RunPulseButton } from "@/components/admin/RunPulseButton";

export const runtime = "edge";
export const dynamic = "force-dynamic";

function pct(n: number, d = 0) { return `${(n * 100).toFixed(d)}%`; }

export default async function InsightsPage() {
  const db = ((process.env as unknown as { DB?: D1Database }).DB ??
    (globalThis as unknown as { DB?: D1Database }).DB) as D1Database | undefined;

  if (!db) {
    return (
      <>
        <header className="admin-header"><h1>Insights</h1></header>
        <p className="muted">Database not bound.</p>
      </>
    );
  }

  const [pulses, current] = await Promise.all([
    listPulses(db).catch(() => []),
    dailyAnomalies(db).catch(() => null),
  ]);

  return (
    <>
      <header className="admin-header" style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
        <h1>Insights</h1>
        <RunPulseButton />
      </header>

      {current && current.anomalies.length > 0 && (
        <section className="admin-card" style={{ borderLeft: "4px solid var(--color-primary, #d04a1a)" }}>
          <h2 style={{ marginTop: 0, fontSize: "1.05em" }}>Right now</h2>
          <ul style={{ margin: 0, paddingLeft: "1.2rem" }}>
            {current.anomalies.map((a, i) => (
              <li key={i} style={{ fontWeight: a.severity === "alert" ? 600 : 400 }}>{a.message}</li>
            ))}
          </ul>
          <p className="muted" style={{ fontSize: "0.85em", marginTop: "0.6rem" }}>
            {current.todayLeads} new lead{current.todayLeads === 1 ? "" : "s"} today.
            Sessions: {current.today.sessions.toLocaleString()}.
            Bounce: {pct(current.today.bounce_rate, 0)}.
            Mobile: {pct(current.today.mobile_share, 0)}.
          </p>
        </section>
      )}

      {current && current.anomalies.length === 0 && (
        <section className="admin-card">
          <h2 style={{ marginTop: 0, fontSize: "1.05em" }}>Right now</h2>
          <p style={{ margin: 0 }}>
            Nothing unusual today.{" "}
            <span className="muted">
              Sessions: {current.today.sessions.toLocaleString()}.
              Leads: {current.todayLeads}.
              Bounce: {pct(current.today.bounce_rate, 0)}.
              Mobile: {pct(current.today.mobile_share, 0)}.
            </span>
          </p>
        </section>
      )}

      <section className="admin-card">
        <h2 style={{ marginTop: 0 }}>Daily Pulse</h2>
        <p className="muted" style={{ fontSize: "0.85em", marginTop: 0 }}>
          A short markdown digest of each day&rsquo;s behavior, generated by the concierge engine after midnight UTC.
          Click &ldquo;Run Pulse&rdquo; in the header to regenerate today&rsquo;s digest on demand.
        </p>
        {pulses.length === 0 ? (
          <p className="muted">No pulses generated yet.</p>
        ) : (
          <ul style={{ listStyle: "none", padding: 0, margin: 0, display: "flex", flexDirection: "column", gap: "1rem" }}>
            {pulses.map((p) => (
              <li key={String(p.id)} style={{
                background: "rgba(255,255,255,0.03)",
                border: "1px solid var(--color-border, rgba(255,255,255,0.1))",
                borderRadius: "0.5rem", padding: "1rem 1.2rem",
              }}>
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline", flexWrap: "wrap", gap: "0.6rem" }}>
                  <h3 style={{ margin: 0, fontSize: "1em" }}>{String(p.pulse_date)}</h3>
                  <span className="muted" style={{ fontSize: "0.85em" }}>
                    {Number(p.sessions)} sessions · {Number(p.leads)} leads · {Number(p.quotes_sent)} quotes sent · {Number(p.quotes_accepted)} accepted
                  </span>
                </div>
                <div style={{ marginTop: "0.5rem", fontSize: "0.95em", whiteSpace: "pre-wrap" }}>
                  {String(p.ai_summary ?? "")}
                </div>
                {(p.top_country || p.top_landing_path || p.top_referrer_host) ? (
                  <div className="muted" style={{ fontSize: "0.78em", marginTop: "0.5rem" }}>
                    {p.top_country ? `Top country: ${String(p.top_country)}` : null}
                    {p.top_landing_path ? ` · Top entry: ${String(p.top_landing_path)}` : null}
                    {p.top_referrer_host ? ` · Top referrer: ${String(p.top_referrer_host)}` : null}
                  </div>
                ) : null}
              </li>
            ))}
          </ul>
        )}
      </section>
    </>
  );
}
